#!/usr/bin/env bash

SNAPSHOTS_DIR="$HOME/snapshots"

# Check if the snapshots directory exists, and create it if it doesn't.
if [ ! -d "$SNAPSHOTS_DIR" ]; then
  mkdir -p "$SNAPSHOTS_DIR"
fi

if [ $# -eq 0 ]; then
  /run/current-system/sw/bin/scrot -o -s /tmp/screenshot.png && /run/current-system/sw/bin/xclip -selection clipboard -t image/png -i /tmp/screenshot.png
else
  NAME="$SNAPSHOTS_DIR/$1.png"
  /run/current-system/sw/bin/scrot -s "$NAME"
fi

