#! /bin/sh

sxhkd &

setxkbmap -option caps:escape

xrdb ~/.Xresources

if echo $(xrandr -q) | grep 'HDMI-1 connected'; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --output HDMI-1 --auto --mode 1920x1080 --above eDP-1
    bspc monitor HDMI-1 -d I II III IV V VI VII
    bspc monitor eDP-1 -d VIII IX X
else
  echo "Done"
    xrandr --output HDMI-1 --off
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

$HOME/.config/polybar/launch.sh &

feh --bg-fill ~/death-star.jpg

bspc config top_padding         -5
bspc config border_width        1
bspc config window_gap          5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
