#!/usr/bin/env bash

sxhkd &

setxkbmap -option caps:escape

xrdb ~/.Xresources

$HOME/.config/bspwm/initial_setup.sh
$HOME/.config/polybar/launch.sh &
$HOME/.config/bspwm/monitor_hotplug.sh &
$HOME/.config/bspwm/battery_notifier.sh &

feh --bg-fill ~/death-star.jpg

bspc config top_padding         -5
bspc config border_width        1
bspc config window_gap          5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
